export enum acao {
    COMPLETO = 'NOME_DO_MEIO',
    NOME_SOBRENOME = 'NOME_E_SOBRENOME',
    USER_COMPLETO = 'NOME_DO_MEIO_UPDATE'
}

export enum event {
    SALVAR_DADOS = 'SALVAR_DADOS',
    DETALHE = 'EXIBIR_DETALHES',
    TIRAR_DO_TOP = 'TIRAR_DO_TOP_10',
    BOTAR_NO_TOP = 'BOTAR_NO_TOP_10',
    ADD_PRESIDENTE = 'ADICIONAR_PRESIDENTE',
    ADD_REPRESENTANTE = 'ADICIONAR_REPRESENTANTE',
    DELETAR_ALUNO = 'DELETAR_ALUNO',
}
